version: '3.8'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: tax-nextjs
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
